name: Python Project CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
    
    - name: Run Pylint
      run: |
        # Run pylint on CALCULATOR directory files
        pylint $(find CALCULATOR -name "*.py")
    
    - name: Run Pytest with Coverage
      run: |
        # Run tests with coverage
        pytest --cov=CALCULATOR --cov-report=xml TESTS/
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      # Note: Codecov token is optional
      continue-on-error: true